
const express = require('express');
const cors = require('cors');
const app = express();
const PORT = process.env.PORT || 10000;

app.use(cors());
app.use(express.json());

app.post('/api/content/generate', (req, res) => {
    const { title, keyword, outline } = req.body;
    res.json({
        content: `Generated content for: ${title}\n\nKeyword: ${keyword}\n\nOutline:\n${outline}`
    });
});

app.post('/api/content/seo', (req, res) => {
    res.json({
        seoScore: Math.floor(Math.random() * 100),
        suggestions: ["Use more keywords", "Improve meta description", "Add internal links"]
    });
});

app.post('/api/content/trading', (req, res) => {
    res.json({
        content: "This is a placeholder for a trading-related article generated by AI."
    });
});

app.get('/api/analytics', (req, res) => {
    res.json({
        totalViews: Math.floor(Math.random() * 10000),
        totalClicks: Math.floor(Math.random() * 1000),
        estimatedEarnings: (Math.random() * 500).toFixed(2)
    });
});

app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});
